name: Deploy IP Groups and FWRCG (After PR Approval)

on:
  workflow_run:
    workflows: ["PR Validation - IP Groups and FWRCG"]
    types:
      - completed

jobs:
  deploy_ip_groups:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy IP Groups
        run: |
          echo "Deploying IP Groups..."

  deploy_fwrcg:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: deploy_ip_groups

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Firewall Rule Collection Groups
        run: |
          echo "Deploying Deploy Firewall Rule Collection Groups..."
