name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: Read variable from artifact
        id: read_var
        run: |
          my_variable=$(cat my_variable.txt)
          echo "my_variable=${my_variable}"
          echo "my_variable=$my_variable" >> $GITHUB_ENV  # Set it as an environment variable

      - name: Use variable
        run: |
          echo "The variable from Workflow 1 is: $my_variable"
